version: "3"
services:
  # app:
  #   build: .
  #   container_name: laundry_app
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_NAME: laundry_db
  #     DB_USER: postgres
  #     DB_PASSWORD: password
  #   ports:
  #     - "8080:8080"

  db:
    image: postgres:13
    container_name: laundry_db
    environment:
      POSTGRES_DB: laundry_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/

volumes:
  db_data:
